CONFIG = {
    'BOT_PREFIX': '!',  # ENTER DESIRED COMMAND PREFIXES (e.g. ! ? $ %)
    'TOKEN': '',  # ENTER DISCORD TOKEN HERE
    'PROFILE_URL': '',  # ENTER YOUR TWITTER PROFILE URL
    'CHANNEL_ID': '',  # ENTER YOUR DISCORD CHANNEL ID
    'INTERVAL': 5  # SECONDS BETWEEN TWITTER SCAN
}
